# This is a TOML document. Boom
[discovery]
    nodes = ["127.0.0.1:7171"]
    region = "sh"
    zone = "sh001"
    host = "comet03" # 这个需要跟[env]下的host一样，job 把这个host当成comet 唯一标识.
    env = "dev"
[env]
    region = "sh"
    zone = "sh001"
    host = "comet02" #这个是保存到redis的server,是logic 把它作为comet标识,发送消息时，会从redis 读出来表明发给哪个comet
    #env = "dev
    DeployEnv = "dev"
[rpcServer]
    addr = ":3109"
    timeout = "1s"

[rpcClient]
    dial = "1s"
    timeout = "1s"

[tcp]
    bind = [":3101"]
    sndbuf = 4096
    rcvbuf = 4096
    keepalive = false
    reader = 32
    readBuf = 1024
    readBufSize = 8192
    writer = 32
    writeBuf = 1024
    writeBufSize = 8192

[websocket]
    bind = [":3102"]
    tlsOpen = false
    tlsBind = [":3103"]
    certFile = "../../cert.pem"
    privateFile = "../../private.pem"

[protocol]
    timer = 32
    timerSize = 2048
    svrProto = 10
    cliProto = 5
    handshakeTimeout = "8s"

[whitelist]
    Whitelist = [123]
    WhiteLog  = "/tmp/white_list.log"

[bucket]
    size = 32
    channel = 1024
    room = 1024
    routineAmount = 32
    routineSize = 1024
